' Developer Express Code Central Example:
' How to do drag and drop items from one ListBoxEdit to another
' 
' This example shows how to implement the drag-and-drop functionality for
' ListBoxEdit.
' 
' First of all, you need to set the AllowDrop
' (http://documentation.devexpress.dev/#WPF/DevExpressXpfCoreDXFrameworkContentElement_AllowDroptopic)
' property to true, in order to let your editor to accept dropping. Next, you'll
' need implement four event handlers for the editor to manage the drag-and-drop
' process:
' 
' 1. MouseLeftButtonDown event handler. Within this handler, it is
' necessary to find out if the click occurred on a certain item. If so, the
' isDragStarted flag is set to True, to allow all the following processing.
' 
' 2.
' PreviewMouseMove event handler. If the isDragStarted flag is set to True, it
' then defines a dragged item and the dragging source object. Then, the
' DragDrop.DoDragDrop() method that initiates a drag-and-drop operation is
' invoked.
' 
' 3. DragOver event handler. Defines the behavior of a drag-and-drop
' operation: if the event's source object can accept a dragged object, the
' e.Effects property is set to the appropriate DragDropEffect value. Otherwise, it
' is set to the DragDropEffects.None value.
' 
' 4. Drop event handler. Handles
' accepting the dragged item by dragging the destination object. Note, that it is
' necessary to create a clone of the copying item to avoid collisions. Do not add
' a dragged item to the items collection itself, until you are sure that this is
' appropriate for your task.
' 
' You can find sample updates and versions for different programming languages here:
' http://www.devexpress.com/example=E3122
'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.225
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Namespace ListBoxDragAndDrop.Properties

    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")>
    Friend NotInheritable Partial Class Settings
        Inherits Global.System.Configuration.ApplicationSettingsBase

        Private Shared defaultInstance As ListBoxDragAndDrop.Properties.Settings = CType((Global.System.Configuration.ApplicationSettingsBase.Synchronized(New ListBoxDragAndDrop.Properties.Settings())), ListBoxDragAndDrop.Properties.Settings)

        Public Shared ReadOnly Property [Default] As Settings
            Get
                Return ListBoxDragAndDrop.Properties.Settings.defaultInstance
            End Get
        End Property
    End Class
End Namespace
